components:
  securitySchemes:
    default:
      flows:
        implicit:
          authorizationUrl: https://test.com
          scopes: {}
      type: oauth2
info:
  description: API Definition of Health API
  title: HealthAPI
  version: 1.0.1
openapi: 3.0.1
paths:
  /query/{category}:
    get:
      parameters:
      - explode: false
        in: path
        name: category
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          description: Default response
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
  /querydoctor/{category}:
    get:
      parameters:
      - explode: false
        in: path
        name: category
        required: true
        schema:
          type: string
        style: simple
      responses:
        default:
          description: Default response
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
security:
- default: []
servers:
- url: http://localhost:8290/healthcare
x-wso2-auth-header: Authorization
x-wso2-basePath: /health/1.0.1
x-wso2-cors:
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
  - authorization
  - Access-Control-Allow-Origin
  - Content-Type
  - SOAPAction
  - apikey
  - Internal-Key
  accessControlAllowMethods:
  - GET
  - PUT
  - POST
  - DELETE
  - PATCH
  - OPTIONS
  accessControlAllowOrigins:
  - '*'
  corsConfigurationEnabled: false
x-wso2-production-endpoints:
  type: http
  urls:
  - http://localhost:8290/healthcare
x-wso2-response-cache:
  cacheTimeoutInSeconds: 300
  enabled: false
x-wso2-sandbox-endpoints:
  type: http
  urls:
  - http://localhost:8290/healthcare
x-wso2-transports:
- http
- https
